# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f228d856a812f5307ab76ba141b8afe0b9d96f0bc5725c30b185ad4b4b30e7b545ef4f80f9a5e361b4e0260a871b11227ed1cd7e5c04991c12d691b1f99aaa27

test:
  secret_key_base: 580b834c128832352d7ee4607e3bcd7d294db0380d4f1a55495f1c9d767d7fc368f2d48275eca3be426a875b0b7dbb780fd7679e1e732a3612bc42612eaf074a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
